### ISSUE TITLE
Correctly set body background color with theme

### ISSUE THREAD

**Issue by Jaredk3nt** [FortellisDev/Ossus#3]
Currently the background-color is not being set properly so it appears grey by default on firefox windows and will not change if the theme variables are set to anything other than white.

Acceptance Criteria:
- Background of body changes color based on the given `bg` theme color
- Background of supporting components should also have their background color changed (toc, menu, etc...)

**Comment by brandoboyd** [comment]
Recreated the bug by updating the bg element to bright green (#00FF3E) in the following file: /nodemodules/ossus_components/dist/defaultTheme.js

`var color = {
  primary: '#F68A33',
  secondary: '#000',
  grey: '#ccc',
  bg: '#00FF3E',
  bgDark: '#202020',
  fg: '#333',
  fgOnPrimary: '#fff',
  fgOnDark: '#fff'
};`
<img width="542" alt="firefox error-green" src="https://user-images.githubusercontent.com/1005059/52081067-27633280-254e-11e9-9c03-c7a2739fd14d.PNG">

**Comment by Jaredk3nt** [comment]
This should be completely resolved as of last release (`ossus` v1.0.2 & `ossus-components` v1.0.3). `create-ossus` v1.0.3 will include these changes.
